### ISSUE TITLE
Ground speed (between locations) vs calc.speed

### ISSUE THREAD

**Issue by peterdesmet** [inbo/bird-tracking#107]
Is Movebank `ground speed` equal to UvA-BiTS `calc.speed`?

https://github.com/inbo/bird-tracking/blob/25495a0461f72dc69c7cf063779c1f5030aa2ba6/sql/movebank_gps_data.sql#L62

Movebank `ground speed` is defined as (https://www.movebank.org/node/2381#ground_speed):

> The estimated ground speed between consecutive locations.
> example: 7.22
> units: meters per second

UvA-BiTS `calc.speed` is defined as (https://wiki.pubserv.e-ecology.nl/wiki/index.php/Useful_Queries#get_uvagps_track_speed):

Not documented in the UvA-BiTS wiki, but returned by `get_uvagps_track_speed_incl_shared()` which calculates between **current location and previous one**.

@sarahcd: Movebank definition is somewhat vague, but looking at the one for heading (see #106), I guess this speed is based on time/distance of _pos and pos +1_, while ours is based on _pos and pos -1_. Can we map our value for `ground speed` or should we either not provide it or try to calculate it as _pos and pos +1_ to fit definition?

@Wouter-Vansteelant @jshamoun: We already discussed this at https://github.com/inbo/bird-tracking-etl/issues/15#issuecomment-362687283:

> 3. get_uvagps_track_speed.direction = degrees from north if we draw a
   line between previous fix and current one??
   *Yes*

..., but can you confirm that that `calc.speed` = trajectory speed = ground speed between current position and previous one?

**Comment by Wouter-Vansteelant** [comment]
Yes, it is trajectory speed between position i-1 and position i. You can tell by the fact the first entry for each device (ideally for each track session) is NA. If it were calculated from i to i+1 the last entry would be NA.

FYI, in all my analyses I have always only extracted coordinates and other "measurements" from the data table and did all computations of movement statistics with my own code in R. I usually calculate trajectory speed forwards (i to i+1) rather than backwards (i to i-1) because that feels more intuitive to me. Another option which people sometimes use is to take a running average of trajectory speed in either direction and use that as a measure of local behaviour, but I tend to find this unnecesarily complicates interpretation of movement statistics.

**Comment by peterdesmet** [comment]
@Wouter-Vansteelant choosing not to upload this information to Movebank is a reasonable choice, as it can always be calculated. But if we have that type of information (that is, if it fits the definition), it might be useful for some users. It's a bit of pity that the UvA-BiTS function `get_uvagps_track_speed_incl_shared()` doesn't calculate i to i+1, which seems to be preferred by you and Movebank. Could maybe argue to Ander Astudillo to do so?

**Comment by Wouter-Vansteelant** [comment]
@peterdesmet  I was missing background information that goal is to put uva-bits data into Movebank. That said, is it not so that this column is generated automatically within movebank if you plug in the coordinates? Anyway I am not sure how best to proceed and would encourage you to contact Willem and Ander by email if you think there is a general issue with db. I dont know the reason why traj speed is calculated the way it is in uva-bits.

**Comment by sarahcd** [comment]
As with #106  I'm making the Movebank definition more broad to reflect what people are actually storing. In most cases but not always, the ground speed is coming directly from GPS sensors, which is more complex but typically more accurate than calculating between consecutive locations. Movebank does not calculate values for these fields. Be sure to store in the correct units (m/s); if your the values in your files are in different units you can provide a conversion factor when importing.

**Comment by peterdesmet** [comment]
Movebank `ground-speed` is now mapped to the instantaneous speed measured by the tracker:

https://github.com/inbo/bird-tracking/blob/daae6e9ac0934add7d828720bdc6eb5682903b40/sql/movebank_gps.sql#L91-L93
