### ISSUE TITLE
Compass heading vs direction

### ISSUE THREAD

**Issue by peterdesmet** [inbo/bird-tracking#109]
Is Movebank `compass heading` equal to UvA-BiTS `direction`?

https://github.com/inbo/bird-tracking/blob/25495a0461f72dc69c7cf063779c1f5030aa2ba6/sql/movebank_gps_data.sql#L47

Movebank `compass heading` is defined as (https://www.movebank.org/node/2381#data):

> The tilt-compensated horizontal compass heading.
> example: 62
> units: degrees clockwise from magnetic north

UvA-BiTS `direction` is defined as (https://wiki.pubserv.e-ecology.nl/wiki/index.php/DB_Views_2015#gps.ee_tracking_speed_limited):

> Heading in degrees; 0 is north, 90 is east

@Wouter-Vansteelant @jshamoun: the UvA-BiTS definition is rather sparse, but _is_ this a heading measured by the tag (discussed as "instantaneous heading" at https://github.com/inbo/bird-tracking-etl/issues/15#issuecomment-362687283)? Does it fit the "tilt-compensated horizontal compass heading in degrees clockwise from magnetic north" definition by Movebank?

Note: this heading (assumed to be measured by tag) is different from the calculated trajectory heading discussed in #106.

We already discussed this at https://github.com/inbo/bird-tracking-etl/issues/15#issuecomment-362687283, but can you confirm that UvA-BiTS `calc.heading` is the heading from a current position to a previous one (expressed as degrees from north)?

**Comment by Wouter-Vansteelant** [comment]
@peterdesmet Strictly speaking the heading of a bird is the direction a bird is facing in flight (i.e. orientation of the body) and what is measured between two consecutive points is the "ground direction" achieved including influence of wind. What is appropriately called "direction" in uva-bits (although even less ambiguous would be "track.direction") is confusingly called "heading" in Movebank (although as established in other posts this trajectory metric is calculated from i-1 to i in uva-bits and from pos i to i+1 in movebank). 

One coudl theoretically measure the real heading of a bird using a compass. This has not been implemented in uva-bits, but there are certainly tracking studies out there using trackers with a compass, and movebank thus also provides a seperate column for such data in the column "compass heading". In my opinion this only adds to the confusion in terminology, because "heading" is used correctly in the column "compass heading" but not in the column "heading" itself.

**Comment by peterdesmet** [comment]
Thanks! So the takeaway is that UvA-BiTS `gps.ee_tracking_speed_limited.direction` should not be mapped to `compass heading`. What remains then is:

What is the difference (if any) between:

- `gps.ee_tracking_speed_limited.direction`
- `get_uvagps_track_speed.direction`: the direction discussed in #106

**Comment by Wouter-Vansteelant** [comment]
I believe that the column "gps.ee_tracking_speed_limited.direction" is the value generated by the function "get_uvagps...direction". Same applies for column "speed" as output of function "get_uvagps...speed" applied to your particular set of data points. Seems to me the function is applied automatically as coordinates of consecutive fixes are downloaded from tags and stored in db. There is then the option for users to use the function in any query as well, although I dont see why it would generate a different result from the column provided in the db.

**Comment by peterdesmet** [comment]
Thanks, I'll compare a subset of records to see if there are any differences for both forms of `heading` and `speed`.

**Comment by peterdesmet** [comment]
@Wouter-Vansteelant it seems those directions and speeds are different concepts. I've asked the question in the gull tracking mailing list.

<img width="648" alt="screenshot 2018-10-30 at 14 35 45" src="https://user-images.githubusercontent.com/600993/47721767-1eae4800-dc51-11e8-89a0-0c9dfbd7aced.png">


`gps.ee_tracking_speed_limited.speed_2d` >> `get_uvagps_track_speed.speed` (calc_speed_for_interval in screenshot)
`gps.ee_tracking_speed_limited.direction` != `get_uvagps_track_speed.direction` (calc_direction in screenshot). It's not a 360 degrees issue either.

**Comment by peterdesmet** [comment]
Closing issue. `gps.ee_tracking_speed_limited.direction` is instantaneous heading (see #106).
