### ISSUE TITLE
Marking outliers

### ISSUE THREAD

**Issue by peterdesmet** [inbo/bird-tracking#110]
Once #105 is resolved, it would be good to automatically mark clear outliers in the data before uploading to Movebank. Those records will then be available but treated differently by Movebank (see https://www.movebank.org/node/2754), e.g. not show them on the map by default.

Outliers have been discussed before (see https://github.com/inbo/bird-tracking-etl/issues/13) and could be based on:

```sql
calc_speed_2d < 0 -- I can't see how this can occur
calc_speed_2d > 33.33333 -- Opted to set at 30m/s
altitude > 10000 -- Too much error on this variable to flag as an outlier
h_accuracy > 1000 -- Wouldn't include this as basis for outlier, for simplicity
date_time > today -- Is taken care of in the query, but those dates will creep up for open ended track sessions
```

So, decision for now could be to just flag on:

```sql
calc.speed > 30
USERFLAG <> 0 -- manually flag records, very rare
```

Which is the speed based returned by `get_uvagps_track_speed_incl_shared()` (#107) between i and i-1.

A more robust alternative (but requires more processing) suggested by @Wouter-Vansteelant in  https://github.com/inbo/bird-tracking-etl/issues/13#issuecomment-327523913 is to flag records were either the forward or backward trajectory speed exceeds 30, which would probably flag not 1, but 3 records compared to the simple flagging suggested above: i, i-1 and i+1, rather than just i.

@Wouter-Vansteelant, is that a correct assessment?

**Comment by peterdesmet** [comment]
Note to self: check and close https://github.com/inbo/data-publication/issues/53 to test if expected records are flagged.

**Comment by Wouter-Vansteelant** [comment]
Your assessment is correct overall, but with regards to outliers I think it is important to leave processing open to users of the data, depending on their research goals. You are likely to use different selection criteria for outliers depending on resolution of tracking data of interest (e.g. altitude can be used for high-res data, not so much for low-res data, as filtering out unrealistic altitudes also leads to removal of fairly accurate horizontal positions). No user should assume any dataset is completely manually cleaned for outliers. Again, much like calculation of movement statistics, I do data cleaning procedures myself in R, and customized for study species/behaviour of interest/sampling intervals/... As for Marsh Harrier publications, for example, I conduct this step also in R.

In my previous recommendation I argued for an **iterative** procedure whereby you calculate movement stats and apply a speed filter up to three times. Whether you use forward or backward trajectory speed, the combination of both, or a running average of both, as a speed filter for outliers is debatable, but I think you cant escape necessity of iteratively applying such a filter. The reason being that sometimes you get several subsequent outliers that are positioned logically relative to each other, so that points in the middle of such a "stray segment" have realistic speed values. By applying filter across few iterations you eat away at one or both ends of such stray segments until all outliers are gone. I have not found any other stats such as vdop or hdop that adequately that allow to filter out such outliers in a single iteration.

It is important to keep in mind I develped this method to deal with migration data! This filter is not adequate for dealing with unrealistic fixes in the overwintering range of honey buzzards, marsh harriers and various other birds I worked on!

In addition, any generic filter will lead to exclusion of realistic data points too, and imho it would go a step to far to store the output of such a filter in the "outlier" column in movebank, precisely because it is defined as a manual annotation of outliers, not a generic one

**Comment by peterdesmet** [comment]
@sarahcd, https://www.movebank.org/node/2754 states:

> These records are defined in Movebank using the data terms manually marked outlier, algorithm marked outlier (for Argos Doppler data only), and visible.

I noticed I can upload data with `algorithm-marked-outlier`, but that these are **not** automatically set to `visible=false`. Is this because `algorithm-marked-outlier` is reserved for ARGOS data only and I should not use the field?

**Comment by peterdesmet** [comment]
@sarahcd, you can ignore my question. I see you already answered it here: https://github.com/inbo/bird-tracking/issues/105#issuecomment-435185249 and that `algorithm-marked-outlier` should not be used. I also noticed it is (correctly) no longer available in the GUI.

**Comment by peterdesmet** [comment]
@Wouter-Vansteelant very late reply from me, but thanks for the explanation. We've decided not to automatically mark any records as outliers or import them as such in movebank. The only `outlier` annotation we will import into movebank is `userflag=TRUE`.
