### ISSUE TITLE
Wrong timestamps H_GRONINGEN dataset on movebank

### ISSUE THREAD

**Issue by milotictanja** [inbo/bird-tracking#118]
The Western marsh harriers from Groningen are migrating into the future as some records have future timestamps. 
The dataset downloaded from movebank contains the following date ranges:

animal-id	| number of observations | min date | max date
--------	| ---------------	| -----------------	| -----------
5446465	| 178914	| 2012-01-06	| 2018-07-07
5336455	| 5420	| 2014-04-06	| 2015-11-06
5325667	| 781906	| 2014-01-08	| **2020-07-05**
5327085	| 21337	| 2016-01-07	| 2018-07-08

While the date ranges in the UvA-BiTS dataset is as follows:

animal-id	| number of observations | min date | max date
--------	| ---------------	| -----------------	| -----------
5446465	| 178914	| 2012-05-10	| 2016-08-11
5336455	| 5420	| 2014-06-04	| 2014-06-23
5325667	| 781906	| 2014-07-04	| 2018-07-11
5327085	| 21337	| 2016-06-18	| 2016-09-03

For individual 5325667 future dates are recorded. For all other individuals dates are shifted as well (different min and max dates in movebank and UvA-BiTS datasets). The total number of records doesn't differ between datasets, so no new data have been added.

**Comment by peterdesmet** [comment]
Let's see if addressing #119 solves this

**Comment by peterdesmet** [comment]
The issue was caused by a wrong mapping of day and month. I have reuploaded all files and downloaded them to check:

year | record
--- | ---
2012 | 85,309
2013 | 27,538
2014 | 85,329
2015 | 87,025
2016 | 102,280
2017 | 290,707
2018 | 309,389
Total | 987,577

Which is correct with what I uploaded. The summary numbers displayed are not entirely correct though, but addressing that in #119

**Comment by peterdesmet** [comment]
Note: there are no longer records in the future.
