### ISSUE TITLE
Movebank download: rename fields and add "same as:"

### ISSUE THREAD

**Issue by peterdesmet** [inbo/bird-tracking#132]
@sarahcd, when downloading data from Movebank (to upload them to Zenodo), I noticed that some fields are not named after the recommended attribute in the [Movebank Attribute Dictionary](https://www.movebank.org/node/2381). I listed them below.

**Why not always use the recommended attribute name in the download headers**? Note, I'm not counting differences between `hyphen-notation` and `non hyphen notation` for attribute names (which seem to be used interchangeably).

download file | header in data | recommended attribute | remark
--- | --- | --- | ---
ref data | deploy on date | deploy on timestamp | mentioned in `same as`
ref data | deploy off date | deploy off timestamp | mentioned in `same as`
ref data | tag serial no | tag serial number | mentioned in `same as`
gps data | bar:barometric height | barometric height | mentioned in `same as`
gps data | bar:barometric pressure | barometric pressure | mentioned in `same as`
gps data | gps:dop | GPS DOP | **not** mentioned in `same as` or `alternative label`
gps data | gps:satellite count | GPS satellite count | **not** mentioned in `same as` or `alternative label`
gps data | gps:vdop | GPS VDOP | **not** mentioned in `same as` or `alternative label`
gps data | external temperature | temperature external | **not** mentioned in `same as`. It is mentioned as `alternative label` at http://vocab.nerc.ac.uk/collection/MVB/current/MVB000104/
gps data | height above msl | height above mean sea level | mentioned in `same as`
gps data | individual taxon canonical name | animal taxon | mentioned in `same as`, confusing that it is correctly named `animal taxon` in ref data
gps data | tag local identifier | tag ID | mentioned in `same as`, confusing that it is correctly named `tag id` in ref data
gps data| individual local identifier | animal ID | mentioned in `same as`, confusing that it is correctly named `tag id` in ref data

**Comment by peterdesmet** [comment]
@sarahcd, summary after seeing NERC vocab:

1. `gps:dop`, `gps:satellite count` and `gps:vdop` should be added as `same as` in https://www.movebank.org/node/2381 and `alternative label` at http://vocab.nerc.ac.uk/collection/MVB/current/
2. `external temperature` should be updated at https://www.movebank.org/node/2381
3. It is confusing that the names `tag id`, `animal id` and `animal taxon` are not used in the data export, while they are in the reference data export

**Comment by peterdesmet** [comment]
And also:

4. `tag serial number` is named `tag serial no` at NERC, without an alternative label.

**Comment by sarahcd** [comment]
Thanks, I'll look more closely at your recommendations as we plan some updates for term consistency across the API, data downloads and GUI. A few notes: 
- currently ":" is ignored in documenting attribute names in the same way that "-" is ignored.
- in some cases usage that is not ideal (like animal-id = individual-local-identifier) is basically grandfathered in because it dates back to the beginning of the database, and now other tools/packages have been developed to work with them like they are. 
- in other cases (like height-above-msl and height-above-mean-sea-level) a shorter name is preferred in files while a longer name is preferred in the gui to help make sure users find, understand and use attributes correctly.

**Comment by peterdesmet** [comment]
Hi @sarahcd, hope you're doing well. I'll be closing this issue, as it is something for on Movebank's side. It will remain here for future reference.
